[package]
description = "A Nushell plugin to export data to xlsx files"
edition = "2021"
name = "nu_plugin_to_xlsx"
version = "0.6.0"

[dependencies]
chrono = "0.4"
nu-engine = "0.106.1"
nu-plugin = "0.106.1"
nu-protocol = "0.106.1"
rust_xlsxwriter = "0.52.0"
